name: Build on Push

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v1

      - name: Restore vJoy SDK (if using NuGet or Xcopy)
        run: |
          # Adjust this step if you have a different vJoy SDK installation method
          echo "Ensure vJoyInterface.lib and vJoyInterface.h are available in your include/lib paths"

      - name: Build jctool (Release Win32)
        run: msbuild jctool/jctool.vs2017.vcxproj /p:Configuration=Release /p:Platform=Win32 /verbosity:minimal
